//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IconRipper.Gui.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IconRipper.Gui.Localization.MainWindow", typeof(MainWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        internal static string FileDialog_Ext_All {
            get {
                return ResourceManager.GetString("FileDialog.Ext.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap Image File.
        /// </summary>
        internal static string FileDialog_Ext_Bmp {
            get {
                return ResourceManager.GetString("FileDialog.Ext.Bmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel Item.
        /// </summary>
        internal static string FileDialog_Ext_Cpl {
            get {
                return ResourceManager.GetString("FileDialog.Ext.Cpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Link Library.
        /// </summary>
        internal static string FileDialog_Ext_Dll {
            get {
                return ResourceManager.GetString("FileDialog.Ext.Dll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable File.
        /// </summary>
        internal static string FileDialog_Ext_Exe {
            get {
                return ResourceManager.GetString("FileDialog.Ext.Exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics Interchange Format.
        /// </summary>
        internal static string FileDialog_Ext_Gif {
            get {
                return ResourceManager.GetString("FileDialog.Ext.Gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon File.
        /// </summary>
        internal static string FileDialog_Ext_Ico {
            get {
                return ResourceManager.GetString("FileDialog.Ext.Ico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG Image.
        /// </summary>
        internal static string FileDialog_Ext_Jpg {
            get {
                return ResourceManager.GetString("FileDialog.Ext.Jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Network Graphics.
        /// </summary>
        internal static string FileDialog_Ext_Png {
            get {
                return ResourceManager.GetString("FileDialog.Ext.Png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagged Image File Format.
        /// </summary>
        internal static string FileDialog_Ext_Tiff {
            get {
                return ResourceManager.GetString("FileDialog.Ext.Tiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard (may lose transparency).
        /// </summary>
        internal static string Icon_ContextMenu_CopyToClipboard {
            get {
                return ResourceManager.GetString("Icon.ContextMenu.CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...as BMP.
        /// </summary>
        internal static string Icon_ContextMenu_SaveAsBmp {
            get {
                return ResourceManager.GetString("Icon.ContextMenu.SaveAsBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...as GIF.
        /// </summary>
        internal static string Icon_ContextMenu_SaveAsGif {
            get {
                return ResourceManager.GetString("Icon.ContextMenu.SaveAsGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...as ICO (this resolution only).
        /// </summary>
        internal static string Icon_ContextMenu_SaveAsIco {
            get {
                return ResourceManager.GetString("Icon.ContextMenu.SaveAsIco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...as JPG.
        /// </summary>
        internal static string Icon_ContextMenu_SaveAsJpg {
            get {
                return ResourceManager.GetString("Icon.ContextMenu.SaveAsJpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...as PNG.
        /// </summary>
        internal static string Icon_ContextMenu_SaveAsPng {
            get {
                return ResourceManager.GetString("Icon.ContextMenu.SaveAsPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...as TIFF.
        /// </summary>
        internal static string Icon_ContextMenu_SaveAsTiff {
            get {
                return ResourceManager.GetString("Icon.ContextMenu.SaveAsTiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save this icon....
        /// </summary>
        internal static string Icon_ContextMenu_SaveIcon {
            get {
                return ResourceManager.GetString("Icon.ContextMenu.SaveIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Depth.
        /// </summary>
        internal static string Icon_Info_BitsPerPixel {
            get {
                return ResourceManager.GetString("Icon.Info.BitsPerPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string Icon_Info_Format {
            get {
                return ResourceManager.GetString("Icon.Info.Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Icon_Info_Height {
            get {
                return ResourceManager.GetString("Icon.Info.Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Colors.
        /// </summary>
        internal static string Icon_Info_NumberOfColors {
            get {
                return ResourceManager.GetString("Icon.Info.NumberOfColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit Planes.
        /// </summary>
        internal static string Icon_Info_Planes {
            get {
                return ResourceManager.GetString("Icon.Info.Planes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size (in bytes).
        /// </summary>
        internal static string Icon_Info_Size {
            get {
                return ResourceManager.GetString("Icon.Info.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Info.
        /// </summary>
        internal static string Icon_Info_Title {
            get {
                return ResourceManager.GetString("Icon.Info.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an icon from above.
        /// </summary>
        internal static string Icon_Info_Unselected {
            get {
                return ResourceManager.GetString("Icon.Info.Unselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Icon_Info_Width {
            get {
                return ResourceManager.GetString("Icon.Info.Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by ID (ascending).
        /// </summary>
        internal static string Icon_ReSortButton_Tooltip_Id {
            get {
                return ResourceManager.GetString("Icon.ReSortButton.Tooltip.Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by image quality (descending).
        /// </summary>
        internal static string Icon_ReSortButton_Tooltip_ImageQuality {
            get {
                return ResourceManager.GetString("Icon.ReSortButton.Tooltip.ImageQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} icons in total.
        /// </summary>
        internal static string Icon_StatusBar_Selected {
            get {
                return ResourceManager.GetString("Icon.StatusBar.Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for icon group selection.
        /// </summary>
        internal static string Icon_StatusBar_Unselected {
            get {
                return ResourceManager.GetString("Icon.StatusBar.Unselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an icon group from the left.
        /// </summary>
        internal static string Icon_Unselected {
            get {
                return ResourceManager.GetString("Icon.Unselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...as ICO (all resolutions).
        /// </summary>
        internal static string IconGroup_ContextMenu_SaveAsIco {
            get {
                return ResourceManager.GetString("IconGroup.ContextMenu.SaveAsIco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save this icon group....
        /// </summary>
        internal static string IconGroup_ContextMenu_SaveIconGroup {
            get {
                return ResourceManager.GetString("IconGroup.ContextMenu.SaveIconGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} icon groups in total.
        /// </summary>
        internal static string IconGroup_StatusBar_Loaded {
            get {
                return ResourceManager.GetString("IconGroup.StatusBar.Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for a PE file to load.
        /// </summary>
        internal static string IconGroup_StatusBar_Unloaded {
            get {
                return ResourceManager.GetString("IconGroup.StatusBar.Unloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please load a PE file
        ///Such as Dynamic Link Library (DLL), Executable (EXE), etc
        ///
        ///1. Menu -&gt; File -&gt; Load
        ///2. Menu -&gt; File -&gt; Load Common...
        ///3. Drag it here.
        /// </summary>
        internal static string IconGroup_Unloaded {
            get {
                return ResourceManager.GetString("IconGroup.Unloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Menu_About {
            get {
                return ResourceManager.GetString("Menu.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Page.
        /// </summary>
        internal static string Menu_About_ProjectPage {
            get {
                return ResourceManager.GetString("Menu.About.ProjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Menu_About_Version {
            get {
                return ResourceManager.GetString("Menu.About.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu.File.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Menu_File_Load {
            get {
                return ResourceManager.GetString("Menu.File.Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Common....
        /// </summary>
        internal static string Menu_File_LoadCommon {
            get {
                return ResourceManager.GetString("Menu.File.LoadCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unload.
        /// </summary>
        internal static string Menu_File_Unload {
            get {
                return ResourceManager.GetString("Menu.File.Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Menu_Language {
            get {
                return ResourceManager.GetString("Menu.Language", resourceCulture);
            }
        }
    }
}
